In [ ]:
# numpy = Numerical Python의 약자
# 파이썬의 수치 해석용 라이브러리
# 리스트와 형태가 비슷하나 전혀 다른 성질이니 주의 !
# 빠르고 효율적인 산술 연산을 제공
# 다(n) 차원 (dimension) 배열(array) : n dimension array
# i = row j = column  k = dimension

In [5]:
# 넘파이 배열 다루기
import numpy as np

list1 = [1, 2, 3, 4, 5]

# 1차원 배열 만들기
arr1 = np.array(list1)
arr1
type(arr1)



numpy.ndarray

In [6]:
# list와 array 차이점
print(list1 + list1)
print(arr1 + arr1)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [7]:
arr1 + 10

array([11, 12, 13, 14, 15])

In [8]:
# 2차원 배열 => 각 차원에서 동일한 크기와 구조를 가져야 한다!
# 이중리스트  => [[]]
list2 = [[1,2,3,4,5],[6,7,8,9,10]]
arr2 = np.array(list2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
#### 배열 속성 확인하기
# - 데이터 배열 크기 : 배열 변수명.shape [depth, row, column]
# - 데이터 차원 : 배열변수명.ndim 
# - 데이터 요소개수 : .size
# - 데이터 타입 .dtype

# 차원의 크기를 알려주는 function()
arr2.shape

arr2.ndim

arr2.size

arr2.dtype

dtype('int64')

In [17]:
arr1_int8 = np.array([1,2,3,4,5],dtype=np.int8)
arr1_int8.dtype

dtype('int8')

In [ ]:
arr1_int64 = arr1_int8.astype("int64")
arr1_int64.dtype

dtype('int64')

In [ ]:
## 1~50 까지 있는 배열 자동 function()이 있다.
list3 = []

for i in range(1, 51, 1):
    list3.append(i)
print(list3)

arr3 = np.arange(1,51,1)
arr3


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [27]:
# arr3 를 2차원 배열로 바꿔보자 => 5행 10열의 2차원 배열 => reshape (row, column)
arr3.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
# 넘파이 배열의 인덱싱과 슬라이싱
# indexing and slicing 
# boolean indexing => 논리 연산자를 활용하여 True 값을 출력할 수 있도록 데이터에 접근

In [30]:
# 데이터 접근을 위한 indexing slicing
# 10, 20, 30, 40, 50

# arr4 = np.array([10, 20, 30, 40, 50])
arr4 = np.arange(10, 51, 10)
arr4

array([10, 20, 30, 40, 50])